### ISSUE TITLE
Concepts have an ID but no name

### ISSUE THREAD

**Issue by cadamini** [translate/terminator#14]
Maybe a stupid thing or question but I get confused if I only see numbered concepts. Is there a reason why they don't have a name?

**Comment by unho** [comment]
@cadamini I don't exactly recall.

But from the back of my mind I would say it was intentional. Terminator was created to allow to set terminology, and sometimes there is passionate discussions about it. So imagine a concept for which several terms (concept names) are being discussed, which one is the right one? Also this allows to create the concept before even adding any term.
